In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 100)

In [3]:
survey = pd.read_csv("work_in_progress")

In [4]:
schema = pd.read_csv("survey_results_schema.csv")

In [23]:
survey.head(1)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AIAgentImpactSomewhat agree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIHuman,AIOpen,ConvertedCompYearly,JobSat,num_languages,num_databases,num_platforms,num_frameworks,experience_group,salary_bucket,has_degree,log_salary,remote,is_fulltime
0,1,i am a developer by profession,25-34 years old,"master’s degree (m.a., m.s., m.eng., mba, etc.)",employed,"caring for dependents (children, elderly, etc.)",8.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,14.0,"developer, mobile",20 to 99 employees,people manager,remote,"yes, i influenced the purchase of a substantial addition to the tech stack",work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,fintech,3.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,i'm not sure,i have neither consider or transitioned into a new career or industry,7.0,3.0,ukraine,eur european euro,52800.0,yes,bash/shell (all shells);dart;sql,dart,dart,yes,cloud firestore;postgresql,NaN,NaN,yes,amazon web services (aws);cloudflare;firebase;google cloud;gradle,NaN,NaN,no,NaN,NaN,NaN,yes,android studio;notepad++;visual studio;visual studio code;xcode,NaN,NaN,NaN,NaN,NaN,windows;macos;android,windows;macos;android;ios;ipados,confluence;github;gitlab;jira;markdown file,markdown file,markdown file,"stack overflow;reddit;github (public projects, not private repos);youtube;linkedin;medium",NaN,NaN,yes,openai gpt (chatbot models);openai image generating models;openai reasoning models,NaN,NaN,yes,a few times per week,between 5 and 10 years,i have never participated in q&a on stack overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,neutral,"rarely, almost never","yes, i use ai tools monthly or infrequently",indifferent,neither trust nor distrust,bad at handling complex tasks,learning about a codebase;writing code;search for answers,project planning;deployment and monitoring;learning new concepts or technologies,documenting code;debugging or fixing code;testing code;committing and reviewing code;predictive ...,NaN,NaN,"ai solutions that are almost right, but not quite",no,"yes, i use ai agents at work monthly or infrequently",not at all or minimally,software engineering,ai agents have increased my productivity.;ai agents have reduced the time spent on specific deve...,i am concerned about the accuracy of the information provided by ai agents.;it takes significant...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,the cost of using certain ai agent platforms is a barrier.;i have concerns about the security an...,NaN,when i don’t trust ai’s answers,"troubleshooting, profiling, debugging",61256.0,10.0,3,2,5,0,Senior,Medium,1,11.022833,remote,0

### Skills Features

In [6]:
survey["num_languages"] = (
    survey["LanguageHaveWorkedWith"]
    .fillna("")
    .str.split(";")
    .apply(lambda x: len([i for i in x if i != ""]))
)

survey["num_languages"].head()

0     3
1     1
2     4
3     3
4    14
Name: num_languages, dtype: int64

In [7]:
survey["num_databases"] = (
    survey["DatabaseHaveWorkedWith"]
    .fillna("")
    .str.split(";")
    .apply(lambda x: len([i for i in x if i]))
)

In [8]:
survey["num_platforms"] = (
    survey["PlatformHaveWorkedWith"]
    .fillna("")
    .str.split(";")
    .apply(lambda x: len([i for i in x if i]))
)

In [9]:
survey["num_frameworks"] = (
    survey["WebframeHaveWorkedWith"]
    .fillna("")
    .str.split(";")
    .apply(lambda x: len([i for i in x if i]))
)

In [10]:
survey["num_databases"] = (
    survey["DatabaseHaveWorkedWith"]
    .fillna("")
    .str.split(";")
    .apply(lambda x: len([i for i in x if i]))
)

### Experience Features

In [11]:
survey["YearsCode"] = pd.to_numeric(
    survey["YearsCode"],
    errors="coerce"
)

In [12]:
survey["experience_group"] = pd.cut(
    survey["YearsCode"],
    bins=[0,2,5,10,20,50],
    labels=[
        "Beginner",
        "Junior",
        "Mid",
        "Senior",
        "Expert"
    ]
)

In [13]:
survey["experience_group"].value_counts()

experience_group
Senior      19545
Expert      12130
Mid         10349
Junior       5146
Beginner     1705
Name: count, dtype: int64

### Salary Features

In [14]:
survey["salary_bucket"] = pd.qcut(
    survey["ConvertedCompYearly"],
    q=5,
    labels=[
        "Very Low",
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

In [30]:
survey["salary_bucket"].value_counts()

salary_bucket
High         4884
Very Low     4819
Low          4786
Medium       4754
Very High    4685
Name: count, dtype: int64

In [17]:
import numpy as np

survey["log_salary"] = np.log1p(
    survey["ConvertedCompYearly"]
)

In [ ]:
survey["has_degree"] = (
    survey["EdLevel"]
    .str.contains(
        "Bachelor|Master|Professional|Doctor",
        case=False,
        na=False
    )
    .astype(int)
)

### Work Style Features

In [19]:
survey["remote"] = survey["RemoteWork"]

In [20]:
survey["is_fulltime"] = (
    survey["Employment"]
    .str.contains("full-time", case=False, na=False)
    .astype(int)
)

### AI Features

In [24]:
mapping = {
    "Never":0,
    "Rarely":1,
    "Sometimes":2,
    "Often":3,
    "Daily":4
}

survey["ai_usage_score"] = survey["AISelect"].map(mapping)

### Job Features

In [25]:
def seniority(job):
    if pd.isna(job):
        return "Unknown"

    job = job.lower()

    if "student" in job:
        return "Student"

    elif "intern" in job:
        return "Intern"

    elif "senior" in job:
        return "Senior"

    elif "manager" in job:
        return "Manager"

    elif "lead" in job:
        return "Lead"

    else:
        return "Developer"

survey["seniority"] = survey["DevType"].apply(seniority)

In [26]:
survey["is_manager"] = (
    survey["DevType"]
    .str.contains("manager", case=False, na=False)
    .astype(int)
)

In [27]:
survey.to_csv("with_features.csv", index=False)

In [3]:
survey = pd.read_csv("with_features.csv")

In [12]:
survey.head(2)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AIAgentImpactSomewhat agree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIHuman,AIOpen,ConvertedCompYearly,JobSat,num_languages,num_databases,num_platforms,num_frameworks,experience_group,salary_bucket,has_degree,log_salary,remote,is_fulltime,ai_usage_score,seniority,is_manager,tech_diversity,db_specialist,polyglot
0,1,i am a developer by profession,25-34 years old,"master’s degree (m.a., m.s., m.eng., mba, etc.)",employed,"caring for dependents (children, elderly, etc.)",8.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,14.0,"developer, mobile",20 to 99 employees,people manager,remote,"yes, i influenced the purchase of a substantial addition to the tech stack",work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,fintech,3.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,i'm not sure,i have neither consider or transitioned into a new career or industry,7.0,3.0,ukraine,eur european euro,52800.0,yes,bash/shell (all shells);dart;sql,dart,dart,yes,cloud firestore;postgresql,NaN,NaN,yes,amazon web services (aws);cloudflare;firebase;google cloud;gradle,NaN,NaN,no,NaN,NaN,NaN,yes,android studio;notepad++;visual studio;visual studio code;xcode,NaN,NaN,NaN,NaN,NaN,windows;macos;android,windows;macos;android;ios;ipados,confluence;github;gitlab;jira;markdown file,markdown file,markdown file,"stack overflow;reddit;github (public projects, not private repos);youtube;linkedin;medium",NaN,NaN,yes,openai gpt (chatbot models);openai image generating models;openai reasoning models,NaN,NaN,yes,a few times per week,between 5 and 10 years,i have never participated in q&a on stack overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,neutral,"rarely, almost never","yes, i use ai tools monthly or infrequently",indifferent,neither trust nor distrust,bad at handling complex tasks,learning about a codebase;writing code;search for answers,project planning;deployment and monitoring;learning new concepts or technologies,documenting code;debugging or fixing code;testing code;committing and reviewing code;predictive ...,NaN,NaN,"ai solutions that are almost right, but not quite",no,"yes, i use ai agents at work monthly or infrequently",not at all or minimally,software engineering,ai agents have increased my productivity.;ai agents have reduced the time spent on specific deve...,i am concerned about the accuracy of the information provided by ai agents.;it takes significant...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,the cost of using certain ai agent platforms is a barrier.;i have concerns about the security an...,NaN,when i don’t trust ai’s answers,"troubleshooting, profiling, debugging",61256.0,10.0,3,2,5,0,Senior,Medium,1,11.022833,remote,0,NaN,Developer,0,10,0,0
1,2,i am a developer by profession,25-34 years old,"associate degree (a.a., a.s., etc.)",employed,NaN,2.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,10.0,"developer, back-end",500 to 999 employees,individual contributor,"hybrid (some in-person, leans heavy to flexibility)",no,personal project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,retail and consumer services,10.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,i'm not sure,i have transitioned into a new career and/or industry voluntarily,6.0,5.0,netherlands,eur european euro,90000.0,yes,java,java;python;swift,java,yes,dynamodb;mongodb,dynamodb;mongodb,dynamodb;mongodb,yes,amazon web services (aws);datadog;docker;homebrew;kubernetes;maven (build tool);terraform,amazon web services (aws);datadog;docker;homebrew;kubernetes;maven (build tool);terraform,amazon web services (aws);datadog;docker;homebrew;kubernetes;maven (build tool);terraform,yes,spring boot,spring boot,spring boot,yes,intellij idea;pycharm;visual studio code;xcode,intellij idea;pycharm;visual studio code;xcode,intellij idea;pycharm;visual studio code;xcode,NaN,NaN,NaN,windows;macos;ios;ipados,macos,confluence;github;jira,confluence;github;jira,confluence;github;jira,"stack overflow;discord;reddit;dev.to;hacker news;github (public projects, not private repos);sla...","stack overflow;discord;reddit;dev.to;hacker news;github (public projects, not private repos);sla...","stack overflow;discord;reddit;dev.to;hacker news;github (public projects, not private repos);sla...",yes,openai gpt (chatbot models),openai gpt (chatbot models),openai gpt (chatbot models),not sure/can't remember,multiple times per day,between 10 and 15 years,"infrequently, less than once per year",chat (people);message boards;long-form articles;videos;coding challenges;logic games/puzzles;lis...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,"yes, somewhat",about half of the time,"yes, i use ai tools weekly",indifferent,neither trust nor distrust,bad at handling complex tasks,learning new concepts or technologies,learning about a codebase;project planning;committing and reviewing code;deployment and monitoring,writing code;documenting code;debugging or fixing code;testing code;predictive analytics;search ...,NaN,NaN,"ai solutions that are almost right, but not quite;debugging ai-generated code is more time-consu...",no,"no, and i don't plan to",not at all or minimally,NaN,NaN,it takes significant time and effort to learn how to use ai agents effectively.;the cost of usin...,NaN,i am concerned about the accuracy of the information provided by ai agents.;i have concerns abou...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,when i don’t trust ai’s answers;when i want to fully understand something;when i want to learn b...,all skills. ai is a flop.,104413.0,9.0,1,2,7,1,Mid,High,0,11.556119,"hybrid (some in-person, leans heavy to flexibility)",0,NaN,Developer,0,11,0,0

In [7]:
survey["tech_diversity"] = (
    survey["num_languages"] +
    survey["num_databases"] +
    survey["num_frameworks"] +
    survey["num_platforms"]
)

In [9]:
survey["db_specialist"] = (
    survey["num_databases"] >= 5
).astype(int)

In [11]:
survey["polyglot"] = (
    survey["num_languages"] >= 6
).astype(int)

In [14]:
survey["web_developer"] = (
    survey["num_frameworks"] >= 2
).astype(int)

In [15]:
survey.to_csv("with_features.csv", index=False)