In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 100)

In [2]:
survey = pd.read_csv("with_features.csv")

In [4]:
test_df = survey[survey['ConvertedCompYearly'].isna()]    # This dataframe is for testing the model

In [5]:
test_df = test_df.drop(columns=["ConvertedCompYearly"])

In [6]:
test_df.shape

(24342, 153)

In [3]:
survey = survey.dropna(subset=['ConvertedCompYearly'])

In [4]:
lower = survey["ConvertedCompYearly"].quantile(0.01)
upper = survey["ConvertedCompYearly"].quantile(0.99)

survey = survey[
    survey["ConvertedCompYearly"].between(lower, upper)
]

In [28]:
y = survey["ConvertedCompYearly"]  # Target

In [69]:
survey.head(1)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AIAgentImpactSomewhat agree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIHuman,AIOpen,ConvertedCompYearly,JobSat,num_languages,num_databases,num_platforms,num_frameworks,experience_group,salary_bucket,has_degree,log_salary,remote,is_fulltime,ai_usage_score,seniority,is_manager,tech_diversity,db_specialist,polyglot,web_developer,PrimaryRole,EducationGroup,OrgSizeScore,all_skills
0,1,i am a developer by profession,25-34 years old,"master’s degree (m.a., m.s., m.eng., mba, etc.)",employed,"caring for dependents (children, elderly, etc.)",8.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,14.0,"developer, mobile",20 to 99 employees,people manager,remote,"yes, i influenced the purchase of a substantial addition to the tech stack",work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,fintech,3.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,i'm not sure,i have neither consider or transitioned into a new career or industry,7.0,3.0,ukraine,eur european euro,52800.0,yes,bash/shell (all shells);dart;sql,dart,dart,yes,cloud firestore;postgresql,NaN,NaN,yes,amazon web services (aws);cloudflare;firebase;google cloud;gradle,NaN,NaN,no,NaN,NaN,NaN,yes,android studio;notepad++;visual studio;visual studio code;xcode,NaN,NaN,NaN,NaN,NaN,windows;macos;android,windows;macos;android;ios;ipados,confluence;github;gitlab;jira;markdown file,markdown file,markdown file,"stack overflow;reddit;github (public projects, not private repos);youtube;linkedin;medium",NaN,NaN,yes,openai gpt (chatbot models);openai image generating models;openai reasoning models,NaN,NaN,yes,a few times per week,between 5 and 10 years,i have never participated in q&a on stack overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,neutral,"rarely, almost never","yes, i use ai tools monthly or infrequently",indifferent,neither trust nor distrust,bad at handling complex tasks,learning about a codebase;writing code;search for answers,project planning;deployment and monitoring;learning new concepts or technologies,documenting code;debugging or fixing code;testing code;committing and reviewing code;predictive ...,NaN,NaN,"ai solutions that are almost right, but not quite",no,"yes, i use ai agents at work monthly or infrequently",not at all or minimally,software engineering,ai agents have increased my productivity.;ai agents have reduced the time spent on specific deve...,i am concerned about the accuracy of the information provided by ai agents.;it takes significant...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,the cost of using certain ai agent platforms is a barrier.;i have concerns about the security an...,NaN,when i don’t trust ai’s answers,"troubleshooting, profiling, debugging",61256.0,10.0,3,2,5,0,Senior,Medium,1,11.022833,remote,0,2.0,Developer,0,10,0,0,0,"developer, mobile",Master,2.0,bash/shell (all shells);dart;sql;cloud firestore;postgresql;;amazon web services (aws);cloudflar...

In [5]:
df = survey[
    [
        "ConvertedCompYearly",
        "Country",
        "PrimaryRole",
        "experience_group",
        "seniority",
        "EducationGroup",
        "Employment",
        "YearsCode",
        "WorkExp",
        "OrgSizeScore",
        "ai_usage_score"
    ]
].copy()

In [22]:
test_df.shape

(0, 11)

In [6]:
df.shape, survey.shape

((22542, 11), (22542, 154))

In [46]:
df['ConvertedCompYearly'].mean()

np.float64(86524.26040280366)

In [51]:
df.shape

(22542, 11)

In [34]:
df.isna().sum()

ConvertedCompYearly    0
Country                0
PrimaryRole            0
experience_group       0
seniority              0
EducationGroup         0
Employment             0
YearsCode              0
WorkExp                0
OrgSizeScore           0
ai_usage_score         0
dtype: int64

In [7]:
df['OrgSizeScore'] = df['OrgSizeScore'].fillna(df['OrgSizeScore'].median())

In [8]:
df['ai_usage_score'] = df['ai_usage_score'].fillna(df['ai_usage_score'].median())

In [9]:
df = survey[
    [
        "ConvertedCompYearly",
        "Country",
        "Industry",
        "PrimaryRole",
        "experience_group",
        "seniority",
        "EducationGroup",
        "Employment",
        "YearsCode",
        "WorkExp",
        "OrgSizeScore",
        "ai_usage_score"
    ]
].copy()

In [48]:
df.isna().sum()

ConvertedCompYearly    0
Country                0
Industry               0
PrimaryRole            0
experience_group       0
seniority              0
EducationGroup         0
Employment             0
YearsCode              0
WorkExp                0
OrgSizeScore           0
ai_usage_score         0
dtype: int64

In [10]:
categorical_features = [
    "Country",
    "Industry",
    "PrimaryRole",
    "experience_group",
    "seniority",
    "EducationGroup",
    "Employment"
]

In [11]:
numerical_features = [
    "YearsCode",
    "WorkExp",
    "OrgSizeScore",
    "ai_usage_score"
]

In [66]:
survey.head(1)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AIAgentImpactSomewhat agree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIHuman,AIOpen,ConvertedCompYearly,JobSat,num_languages,num_databases,num_platforms,num_frameworks,experience_group,salary_bucket,has_degree,log_salary,remote,is_fulltime,ai_usage_score,seniority,is_manager,tech_diversity,db_specialist,polyglot,web_developer,PrimaryRole,EducationGroup,OrgSizeScore,all_skills
0,1,i am a developer by profession,25-34 years old,"master’s degree (m.a., m.s., m.eng., mba, etc.)",employed,"caring for dependents (children, elderly, etc.)",8.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,14.0,"developer, mobile",20 to 99 employees,people manager,remote,"yes, i influenced the purchase of a substantial addition to the tech stack",work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,fintech,3.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,i'm not sure,i have neither consider or transitioned into a new career or industry,7.0,3.0,ukraine,eur european euro,52800.0,yes,bash/shell (all shells);dart;sql,dart,dart,yes,cloud firestore;postgresql,NaN,NaN,yes,amazon web services (aws);cloudflare;firebase;google cloud;gradle,NaN,NaN,no,NaN,NaN,NaN,yes,android studio;notepad++;visual studio;visual studio code;xcode,NaN,NaN,NaN,NaN,NaN,windows;macos;android,windows;macos;android;ios;ipados,confluence;github;gitlab;jira;markdown file,markdown file,markdown file,"stack overflow;reddit;github (public projects, not private repos);youtube;linkedin;medium",NaN,NaN,yes,openai gpt (chatbot models);openai image generating models;openai reasoning models,NaN,NaN,yes,a few times per week,between 5 and 10 years,i have never participated in q&a on stack overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,neutral,"rarely, almost never","yes, i use ai tools monthly or infrequently",indifferent,neither trust nor distrust,bad at handling complex tasks,learning about a codebase;writing code;search for answers,project planning;deployment and monitoring;learning new concepts or technologies,documenting code;debugging or fixing code;testing code;committing and reviewing code;predictive ...,NaN,NaN,"ai solutions that are almost right, but not quite",no,"yes, i use ai agents at work monthly or infrequently",not at all or minimally,software engineering,ai agents have increased my productivity.;ai agents have reduced the time spent on specific deve...,i am concerned about the accuracy of the information provided by ai agents.;it takes significant...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,the cost of using certain ai agent platforms is a barrier.;i have concerns about the security an...,NaN,when i don’t trust ai’s answers,"troubleshooting, profiling, debugging",61256.0,10.0,3,2,5,0,Senior,Medium,1,11.022833,remote,0,2.0,Developer,0,10,0,0,0,"developer, mobile",Master,2.0,bash/shell (all shells);dart;sql;cloud firestore;postgresql;;amazon web services (aws);cloudflar...

In [12]:
tech_cols = [
    "LanguageHaveWorkedWith",
    "DatabaseHaveWorkedWith",
    "WebframeHaveWorkedWith",
    "PlatformHaveWorkedWith",
    "DevEnvsHaveWorkedWith",
    "AIModelsHaveWorkedWith"
]

survey[tech_cols].head()

,LanguageHaveWorkedWith,DatabaseHaveWorkedWith,WebframeHaveWorkedWith,PlatformHaveWorkedWith,DevEnvsHaveWorkedWith,AIModelsHaveWorkedWith
0,bash/shell (all shells);dart;sql,cloud firestore;postgresql,NaN,amazon web services (aws);cloudflare;firebase;...,android studio;notepad++;visual studio;visual ...,openai gpt (chatbot models);openai image gener...
1,java,dynamodb;mongodb,spring boot,amazon web services (aws);datadog;docker;homeb...,intellij idea;pycharm;visual studio code;xcode,openai gpt (chatbot models)
2,dart;html/css;javascript;typescript,mongodb;mysql;postgresql,next.js;node.js;react,datadog;firebase;npm;pnpm,visual studio code,gemini (flash general purpose models);openai g...
3,java;kotlin;sql,NaN,spring boot,amazon web services (aws);google cloud,NaN,NaN
4,c;c#;c++;delphi;html/css;java;javascript;lua;p...,elasticsearch;microsoft sql server;mysql;oracl...,angular;asp.net;asp.net core;flask;jquery,amazon web services (aws);apt;docker;make;mave...,eclipse;intellij idea;jupyter notebook/jupyter...,openai gpt (chatbot models)

In [13]:
survey["all_skills"] = (
    survey[tech_cols]
    .fillna("")
    .agg(";".join, axis=1)
)

In [14]:
skills_encoded = (
    survey["all_skills"]
    .str.get_dummies(sep=";")
)

In [74]:
skills_encoded

,ada,aider,alibaba cloud qwen models,amazon redshift,amazon titan models,amazon web services (aws),android studio,angular,angularjs,ansible,anthropic: claude sonnet,apt,asp.net,asp.net core,assembly,astro,axum,bash/shell (all shells),bigquery,blazor,bolt,bun,c,c#,c++,cargo,cassandra,chocolatey,claude code,clickhouse,cline and/or roo,cloud firestore,cloudflare,cobol,cockroachdb,cohere: command a,composer,cosmos db,cursor,dart,databricks sql,datadog,datomic,deepseek (r- reasoning models),deepseek (v- general purpose models),delphi,deno,digital ocean,django,docker,drupal,duckdb,dynamodb,eclipse,elasticsearch,elixir,erlang,express,f#,fastapi,fastify,firebase,firebase realtime database,flask,fortran,gdscript,gemini (flash general purpose models),gemini (pro reasoning models),gleam,go,google cloud,gradle,groovy,h2,heroku,homebrew,html/css,ibm cloud,ibm db2,influxdb,intellij idea,java,javascript,jquery,jupyter notebook/jupyterlab,kotlin,kubernetes,laravel,lisp,lovable.dev,lua,make,mariadb,matlab,maven (build tool),meta llama (all models),micropython,microsoft access,microsoft azure,microsoft phi-4 models,microsoft sql server,mistral ai models,mojo,mongodb,msbuild,mysql,nano,neo4j,neovim,nestjs,netlify,new relic,next.js,ninja,node.js,notepad++,npm,nuget,nuxt.js,ocaml,openai gpt (chatbot models),openai image generating models,openai reasoning models,oracle,pacman,perl,perplexity sonar models,phoenix,php,phpstorm,pip,pnpm,pocketbase,podman,poetry,postgresql,powershell,prolog,prometheus,pycharm,python,r,railway,react,redis,reka (flash 3 or other reka models),rider,ruby,ruby on rails,rust,rustrover,scala,snowflake,splunk,spring boot,sql,sqlite,sublime text,supabase,svelte,swift,symfony,terraform,trae,typescript,valkey,vba,vercel,vim,visual basic (.net),visual studio,visual studio code,vite,vscodium,vue.js,webpack,webstorm,windsurf,wordpress,x grok models,xcode,yandex cloud,yarn,zed,zig
0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,0,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,1,1,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,1,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47224,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0
47225,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,1,0,0,0,0
47227,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
47231,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
47234,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [16]:
categorical_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "onehot",
            OneHotEncoder(handle_unknown="ignore")
        )
    ]
)

In [17]:
numerical_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)

In [18]:
skill_features = skills_encoded.columns.tolist()

In [19]:
skill_transformer = "passthrough"

In [20]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            categorical_transformer,
            categorical_features
        ),
        (
            "num",
            numerical_transformer,
            numerical_features
        ),
         (
            "skills",
            "passthrough",
            skill_features
        )
    ],
    remainder="drop"
)

In [21]:
preprocessor

ColumnTransformer(transformers=[('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Country', 'Industry', 'PrimaryRole',
                                  'experience_group', 'seniority',
                                  'EducationGroup', 'Employment']),
                                ('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler...
                                 ['ada', 'aider', 'alibaba cloud qwen models',
                                  'amazon redshift', 'amazon titan models',
                                  'amazon web services (aws)', 'android studio',
                                  'angular', 'angularjs', 'ansible',
                                  'anthropic: claude sonnet', 'apt', 'asp.net',
                                  'asp.net core', 'assembly', 'astro', 'axum',
                                  'bash/shell (all shells)', 'bigquery',
                                  'blazor', 'bolt', 'bun', 'c', 'c#', 'c++',
                                  'cargo', 'cassandra', 'chocolatey',
                                  'claude code', 'clickhouse', ...])])

In [22]:
df.index.equals(skills_encoded.index)

True

In [23]:
survey.index.equals(skills_encoded.index)

True

In [24]:
X_base = df[
    categorical_features + numerical_features
]

In [25]:
X = pd.concat(
    [
        X_base.reset_index(drop=True),
        skills_encoded.reset_index(drop=True)
    ],
    axis=1
)

In [26]:
y = df["ConvertedCompYearly"].reset_index(drop=True)

In [27]:
X.shape, y.shape

((22542, 196), (22542,))

### Train Test Split

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(18033, 196)
(4509, 196)

### Linear Regression Model

In [29]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

lr_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

lr_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Country', 'Industry',
                                                   'PrimaryRole',
                                                   'experience_group',
                                                   'seniority',
                                                   'EducationGroup',
                                                   'Employment']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='me...
                                                   'amazon redshift',
                                                   'amazon titan models',
                                                   'amazon web services (aws)',
                                                   'android studio', 'angular',
                                                   'angularjs', 'ansible',
                                                   'anthropic: claude sonnet',
                                                   'apt', 'asp.net',
                                                   'asp.net core', 'assembly',
                                                   'astro', 'axum',
                                                   'bash/shell (all shells)',
                                                   'bigquery', 'blazor', 'bolt',
                                                   'bun', 'c', 'c#', 'c++',
                                                   'cargo', 'cassandra',
                                                   'chocolatey', 'claude code',
                                                   'clickhouse', ...])])),
                ('model', LinearRegression())])

In [30]:
lr_pred = lr_model.predict(X_test)

In [31]:
import joblib

joblib.dump(lr_model, "lr_salary_model.pkl")

['lr_salary_model.pkl']

In [32]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

lr_mae = mean_absolute_error(y_test, lr_pred)
lr_rmse = mean_squared_error(y_test, lr_pred) ** 0.5
lr_r2 = r2_score(y_test, lr_pred)

print("MAE :", lr_mae)
print("RMSE:", lr_rmse)
print("R²  :", lr_r2)

MAE : 30320.908727914077
RMSE: 45569.304766019515
R²  : 0.5657875264292302

In [33]:
from sklearn.ensemble import RandomForestRegressor

rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ))
])

rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Country', 'Industry',
                                                   'PrimaryRole',
                                                   'experience_group',
                                                   'seniority',
                                                   'EducationGroup',
                                                   'Employment']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='me...
                                                   'amazon web services (aws)',
                                                   'android studio', 'angular',
                                                   'angularjs', 'ansible',
                                                   'anthropic: claude sonnet',
                                                   'apt', 'asp.net',
                                                   'asp.net core', 'assembly',
                                                   'astro', 'axum',
                                                   'bash/shell (all shells)',
                                                   'bigquery', 'blazor', 'bolt',
                                                   'bun', 'c', 'c#', 'c++',
                                                   'cargo', 'cassandra',
                                                   'chocolatey', 'claude code',
                                                   'clickhouse', ...])])),
                ('model',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])

In [34]:
joblib.dump(rf_model, "rf_salary_model.pkl")

['rf_salary_model.pkl']

In [63]:
rf_pred = rf_model.predict(X_test)

In [64]:
rf_mae = mean_absolute_error(y_test, rf_pred)
rf_rmse = mean_squared_error(y_test, rf_pred) ** 0.5
rf_r2 = r2_score(y_test, rf_pred)

print("MAE :", rf_mae)
print("RMSE:", rf_rmse)
print("R²  :", rf_r2)

MAE : 30098.73006215347
RMSE: 45474.05057214176
R²  : 0.5676009107263387

In [35]:
from xgboost import XGBRegressor

xgb_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        random_state=42,
        objective="reg:squarederror"
    ))
])

xgb_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Country', 'Industry',
                                                   'PrimaryRole',
                                                   'experience_group',
                                                   'seniority',
                                                   'EducationGroup',
                                                   'Employment']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='me...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=6, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=300, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [36]:
joblib.dump(xgb_model, "xgb_salary_model.pkl")

['xgb_salary_model.pkl']

In [66]:
xgb_pred = xgb_model.predict(X_test)

In [67]:
xgb_mae = mean_absolute_error(y_test, xgb_pred)
xgb_rmse = mean_squared_error(y_test, xgb_pred) ** 0.5
xgb_r2 = r2_score(y_test, xgb_pred)

print("MAE :", xgb_mae)
print("RMSE:", xgb_rmse)
print("R²  :", xgb_r2)

MAE : 29307.377307471375
RMSE: 44502.597471873036
R²  : 0.5858780885991701

In [68]:
import pandas as pd

results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "XGBoost"
    ],
    "MAE": [
        lr_mae,
        rf_mae,
        xgb_mae
    ],
    "RMSE": [
        lr_rmse,
        rf_rmse,
        xgb_rmse
    ],
    "R²": [
        lr_r2,
        rf_r2,
        xgb_r2
    ]
})

results.sort_values("R²", ascending=False)

               Model           MAE          RMSE        R²
2            XGBoost  29307.377307  44502.597472  0.585878
1      Random Forest  30098.730062  45474.050572  0.567601
0  Linear Regression  30320.908728  45569.304766  0.565788

## Using model on test_df

In [ ]:
tech_cols = [
    "LanguageHaveWorkedWith",
    "DatabaseHaveWorkedWith",
    "WebframeHaveWorkedWith",
    "PlatformHaveWorkedWith",
    "DevEnvsHaveWorkedWith",
    "AIModelsHaveWorkedWith"
]

test_df[tech_cols].head()

In [71]:
test_df["all_skills"] = (
    test_df[tech_cols]
    .fillna("")
    .agg(";".join, axis=1)
)

In [72]:
skills_encoded = (
    test_df["all_skills"]
    .str.get_dummies(sep=";")
)

In [73]:
skill_features = skills_encoded.columns.tolist()

In [74]:
X_base = test_df[
    categorical_features + numerical_features
]

In [76]:
T = pd.concat(
    [
        X_base.reset_index(drop=True),
        skills_encoded.reset_index(drop=True)
    ],
    axis=1
)

In [77]:
xgb_pred = xgb_model.predict(T)

In [80]:
Salary = xgb_pred

In [85]:
import pandas as pd

Salary_df = pd.DataFrame(Salary, columns=["PredictedSalary"])

combined_df = pd.concat(
    [test_df.reset_index(drop=True),
     Salary_df.reset_index(drop=True)],
    axis=1
)

In [90]:
combined_df.shape

(24342, 155)