In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 100)

In [2]:
survey = pd.read_csv("survey_results_public.csv")

In [3]:
schema = pd.read_csv("survey_results_schema.csv")

In [5]:
survey.head(2)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning new coding techniques or programming language",Online Courses or Certification (includes all media types);Other online resources (e.g. standard...,"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantial addition to the tech stack",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a new career or industry,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;Google Cloud;Gradle,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn;Medium",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image generating models;openAI Reasoning models,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search for answers,Project planning;Deployment and monitoring;Learning new concepts or technologies,Documenting code;Debugging or fixing code;Testing code;Committing and reviewing code;Predictive ...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI agents have reduced the time spent on specific deve...,AI agents have helped me automate repetitive tasks.;AI agents have improved the quality of my co...,NaN,NaN,NaN,I am concerned about the accuracy of the information provided by AI agents.;It takes significant...,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and...,The cost of using certain AI agent platforms is a barrier.;I have concerns about the security an...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning new coding techniques or programming language",Online Courses or Certification (includes all media types);Other online resources (e.g. standard...,"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibility)",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or industry voluntarily,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,"Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Sla...","Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Sla...","Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Sla...",NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form articles;Videos;Coding challenges;Logic games/puzzles;Lis...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Committing and reviewing code;Deployment and monitoring,Writing code;Documenting code;Debugging or fixing code;Testing code;Predictive analytics;Search ...,NaN,NaN,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of usin...,NaN,I am concerned about the accuracy of the information provided by AI agents.;I have concerns abou...,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn b...,All skills. AI is a flop.,104413.0,9.0

In [7]:
schema.head()

     qid          qname                                                                                  question type                                      sub  sq_id
0  QID18  TechEndorse_1  What attracts you to a technology or causes you to endorse it (most to least important)?   RO  AI integration or AI Agent capabilities    1.0
1  QID18  TechEndorse_2  What attracts you to a technology or causes you to endorse it (most to least important)?   RO                          Easy-to-use API    2.0
2  QID18  TechEndorse_3  What attracts you to a technology or causes you to endorse it (most to least important)?   RO                  Robust and complete API    3.0
3  QID18  TechEndorse_4  What attracts you to a technology or causes you to endorse it (most to least important)?   RO     Customizable and manageable codebase    4.0
4  QID18  TechEndorse_5  What attracts you to a technology or causes you to endorse it (most to least important)?   RO                   Reputation for quality    5.0

In [15]:
survey.memory_usage(deep=True).sum() / 1024**2

np.float64(356.62627601623535)

In [17]:
survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49123 entries, 0 to 49122
Columns: 170 entries, ResponseId to JobSat
dtypes: float64(50), int64(1), object(119)
memory usage: 63.7+ MB

## Data Cleaning

In [4]:
# Missing values in each column
missing_count = survey.isnull().sum()

In [5]:
missing_count.sort_values(ascending=False)

AIAgentObsWrite      48859
SOTagsWant Entry     48693
SOTagsHaveEntry      48666
AIModelsWantEntry    48649
AIAgentOrchWrite     48646
                     ...
EdLevel               1036
Employment             846
MainBranch               0
Age                      0
ResponseId               0
Length: 170, dtype: int64

In [6]:
missing_percent = (survey.isnull().sum() / len(survey)) * 100

missing_percent.sort_values(ascending=False)

AIAgentObsWrite      99.462574
SOTagsWant Entry     99.124646
SOTagsHaveEntry      99.069682
AIModelsWantEntry    99.035075
AIAgentOrchWrite     99.028968
                       ...
EdLevel               2.108992
Employment            1.722208
MainBranch            0.000000
Age                   0.000000
ResponseId            0.000000
Length: 170, dtype: float64

In [7]:
missing_report = pd.DataFrame({
    "Missing Count": survey.isnull().sum(),
    "Missing %": round((survey.isnull().sum() / len(survey)) * 100, 2),
    "Data Type": survey.dtypes
})

missing_report = missing_report.sort_values(
    by="Missing %",
    ascending=False
)

missing_report.head()

                   Missing Count  Missing % Data Type
AIAgentObsWrite            48859      99.46    object
SOTagsWant Entry           48693      99.12    object
SOTagsHaveEntry            48666      99.07    object
AIModelsWantEntry          48649      99.04    object
AIAgentOrchWrite           48646      99.03    object

In [8]:
empty_strings = (survey == "").sum()

empty_strings = empty_strings[empty_strings > 0]

empty_strings.sort_values(ascending=False)

Series([], dtype: int64)

In [ ]:
prefer_not = {}

for col in survey.columns:
    if survey[col].dtype == "object":
        count = survey[col].astype(str).str.contains(
            "Prefer",
            case=False,
            na=False
        ).sum()

        if count > 0:
            prefer_not[col] = count

pd.DataFrame.from_dict(
    prefer_not,
    orient="index",
    columns=["Count"]
).sort_values(
    by="Count",
    ascending=False
)

                      Count
Employment              518
Age                     378
AIExplain               157
AIOpen                   17
TechEndorse_13_TEXT       6
TechOppose_15_TEXT        1
JobSatPoints_15_TEXT      1
DatabaseHaveEntry         1
CommPlatformHaveEntr      1
AIModelsWantEntry         1

In [11]:
missing_keywords = [
    "NA",
    "N/A",
    "None",
    "Unknown",
    "Not applicable",
    "Prefer not to say",
    "I prefer not to say"
]

for keyword in missing_keywords:
    print(f"\n{keyword}")

    for col in survey.select_dtypes(include="object"):

        count = survey[col].astype(str).str.fullmatch(
            keyword,
            case=False,
            na=False
        ).sum()

        if count > 0:
            print(f"{col}: {count}")

NA
TechEndorse_13_TEXT: 1
LanguagesHaveEntry: 1
LanguagesWantEntry: 1
DatabaseHaveEntry: 2
DatabaseWantEntry: 1
PlatformHaveEntry: 1
PlatformWantEntry: 1
WebframeHaveEntry: 1
WebframeWantEntry: 1
DevEnvHaveEntry: 1
DevEnvWantEntry: 1
SOTagsHaveEntry: 1
SOTagsWant Entry: 1
OfficeStackHaveEntry: 1
AIExplain: 2
AIAgentKnowWrite: 2
AIAgentOrchWrite: 1
AIAgentObsWrite: 1
AIAgentExtWrite: 1

N/A

None
JobSatPoints_15_TEXT: 2
LanguagesHaveEntry: 2
LanguagesWantEntry: 1
DatabaseHaveEntry: 3
DatabaseWantEntry: 3
PlatformHaveEntry: 2
PlatformWantEntry: 2
WebframeHaveEntry: 2
WebframeWantEntry: 3
DevEnvHaveEntry: 3
DevEnvWantEntry: 3
SOTagsHaveEntry: 4
SOTagsWant Entry: 4
OfficeStackHaveEntry: 2
OfficeStackWantEntry: 2
CommPlatformHaveEntr: 2
CommPlatformWantEntr: 2
AIModelsHaveEntry: 1
AIModelsWantEntry: 1
SO_Actions_15_TEXT: 6
AIExplain: 3
AIAgentOrchWrite: 7
AIAgentObsWrite: 7
AIOpen: 12

Unknown
AIExplain: 1
AIOpen: 1

Not applicable
JobSatPoints_15_TEXT: 1
AIAgentKnowWrite: 1
AIAgentOrchWrite: 1
AIAgentObsWrite: 1

Prefer not to say
Age: 378

I prefer not to say
Employment: 518

In [12]:
survey.replace(
    [
    "NA",
    "N/A",
    "None",
    "Unknown",
    "Not applicable",
    "Prefer not to say",
    "I prefer not to say"
    ],
    np.nan,
    inplace=True
)

In [13]:
survey.isnull().sum()

ResponseId                 0
MainBranch                 0
Age                      378
EdLevel                 1036
Employment              1364
                       ...
AIAgentExtWrite        48265
AIHuman                19956
AIOpen                 26604
ConvertedCompYearly    25195
JobSat                 22480
Length: 170, dtype: int64

In [14]:
missing_keywords = [
    "NA",
    "N/A",
    "None",
    "Unknown",
    "Not applicable",
    "Prefer not to say",
    "I prefer not to say"
]

for keyword in missing_keywords:
    print(f"\n{keyword}")

    for col in survey.select_dtypes(include="object"):

        count = survey[col].astype(str).str.fullmatch(
            keyword,
            case=False,
            na=False
        ).sum()

        if count > 0:
            print(f"{col}: {count}")

NA
TechEndorse_13_TEXT: 1
LanguagesHaveEntry: 1
LanguagesWantEntry: 1
DatabaseHaveEntry: 2
DatabaseWantEntry: 1
PlatformHaveEntry: 1
PlatformWantEntry: 1
WebframeHaveEntry: 1
WebframeWantEntry: 1
DevEnvHaveEntry: 1
DevEnvWantEntry: 1
SOTagsHaveEntry: 1
SOTagsWant Entry: 1
OfficeStackHaveEntry: 1
AIExplain: 2
AIAgentKnowWrite: 2
AIAgentOrchWrite: 1
AIAgentObsWrite: 1
AIAgentExtWrite: 1

N/A

None
JobSatPoints_15_TEXT: 2
LanguagesHaveEntry: 2
LanguagesWantEntry: 1
DatabaseHaveEntry: 3
DatabaseWantEntry: 3
PlatformHaveEntry: 2
PlatformWantEntry: 2
WebframeHaveEntry: 2
WebframeWantEntry: 3
DevEnvHaveEntry: 3
DevEnvWantEntry: 3
SOTagsHaveEntry: 4
SOTagsWant Entry: 4
OfficeStackHaveEntry: 2
OfficeStackWantEntry: 2
CommPlatformHaveEntr: 2
CommPlatformWantEntr: 2
AIModelsHaveEntry: 1
AIModelsWantEntry: 1
SO_Actions_15_TEXT: 6
AIExplain: 3
AIAgentOrchWrite: 7
AIAgentObsWrite: 7
AIOpen: 12

Unknown

Not applicable

Prefer not to say

I prefer not to say

In [15]:
missing_summary = pd.DataFrame({
    "Missing Count": survey.isna().sum(),
    "Missing %": round(survey.isna().mean() * 100, 2),
    "Data Type": survey.dtypes
})

missing_summary = (
    missing_summary[missing_summary["Missing Count"] > 0]
    .sort_values("Missing %", ascending=False)
)

missing_summary

                   Missing Count  Missing % Data Type
AIAgentObsWrite            48860      99.46    object
SOTagsWant Entry           48693      99.12    object
SOTagsHaveEntry            48666      99.07    object
AIModelsWantEntry          48649      99.04    object
AIAgentOrchWrite           48647      99.03    object
...                          ...        ...       ...
LearnCodeAI                 3970       8.08    object
LearnCodeChoose             2322       4.73    object
Employment                  1364       2.78    object
EdLevel                     1036       2.11    object
Age                          378       0.77    object

[168 rows x 3 columns]

In [6]:
numeric_cols = survey.select_dtypes(include="number").columns
categorical_cols = survey.select_dtypes(include="object").columns

print("Numeric columns:", len(numeric_cols))
print("Categorical columns:", len(categorical_cols))

Numeric columns: 50
Categorical columns: 84

In [ ]:
survey[numeric_cols].isna().mean().sort_values(ascending=False)

NameError: name 'survey' is not defined

In [19]:
survey[categorical_cols].head(2)

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,Industry,AIThreat,NewRole,Country,Currency,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AIAgentImpactSomewhat agree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIHuman,AIOpen
0,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)","Yes, I am not new to coding but am learning new coding techniques or programming language",Online Courses or Certification (includes all media types);Other online resources (e.g. standard...,"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantial addition to the tech stack",Work,Fintech,I'm not sure,I have neither consider or transitioned into a new career or industry,Ukraine,EUR European Euro,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;Google Cloud;Gradle,NaN,NaN,No,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,"Stack Overflow;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn;Medium",NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image generating models;openAI Reasoning models,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Overflow,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search for answers,Project planning;Deployment and monitoring;Learning new concepts or technologies,Documenting code;Debugging or fixing code;Testing code;Committing and reviewing code;Predictive ...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,AI agents have increased my productivity.;AI agents have reduced the time spent on specific deve...,I am concerned about the accuracy of the information provided by AI agents.;It takes significant...,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and...,The cost of using certain AI agent platforms is a barrier.;I have concerns about the security an...,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging"
1,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,"Yes, I am not new to coding but am learning new coding techniques or programming language",Online Courses or Certification (includes all media types);Other online resources (e.g. standard...,"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibility)",No,Personal Project,Retail and Consumer Services,I'm not sure,I have transitioned into a new career and/or industry voluntarily,Netherlands,EUR European Euro,Yes,Java,Java;Python;Swift,Java,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,Yes,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Yes,Spring Boot,Spring Boot,Spring Boot,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,"Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Sla...","Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Sla...","Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Sla...",Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form articles;Videos;Coding challenges;Logic games/puzzles;Lis...,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Committing and reviewing code;Deployment and monitoring,Writing code;Documenting code;Debugging or fixing code;Testing code;Predictive analytics;Search ...,NaN,NaN,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of usin...,NaN,I am concerned about the accuracy of the information provided by AI agents.;I have concerns abou...,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and...,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn b...,All skills. AI is a flop.

In [27]:
survey['Age'].value_counts()

Age
25-34 years old      16485
35-44 years old      13232
18-24 years old       9195
45-54 years old       6265
55-64 years old       2626
65 years or older      942
Prefer not to say      378
Name: count, dtype: int64

In [20]:
survey.shape

(49123, 134)

In [19]:
threshold = 0.80

survey = survey.loc[
    :,
    survey.isna().mean() <= threshold
]

# Dropped columns with > 80% missing values

In [38]:
survey.dtypes.value_counts()

object     83
float64    50
int64       1
Name: count, dtype: int64

In [5]:
missing_summary = pd.DataFrame({
    "Missing Count": survey.isna().sum(),
    "Missing %": round(survey.isna().mean() * 100, 2),
    "Data Type": survey.dtypes
})

missing_summary = (
    missing_summary[missing_summary["Missing Count"] > 0]
    .sort_values("Missing %", ascending=False)
)

missing_summary

                                    Missing Count  Missing % Data Type
AIAgentImpactSomewhat agree                 38988      79.37    object
AIToolCurrently mostly AI                   37913      77.18    object
AIModelsAdmired                             37851      77.05    object
AIModelsWantToWorkWith                      37291      75.91    object
AIAgentChallengesSomewhat disagree          37007      75.34    object
...                                           ...        ...       ...
TechEndorse_6                               13180      26.83   float64
TechEndorse_7                               13180      26.83   float64
TechEndorse_8                               13180      26.83   float64
TechEndorse_9                               13180      26.83   float64
EmploymentAddl                               4303       8.76    object

[114 rows x 3 columns]

In [57]:
survey.head(1)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AIAgentImpactSomewhat agree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning new coding techniques or programming language",Online Courses or Certification (includes all media types);Other online resources (e.g. standard...,"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantial addition to the tech stack",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,Fintech,3.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,I'm not sure,I have neither consider or transitioned into a new career or industry,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;Google Cloud;Gradle,NaN,NaN,No,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,"Stack Overflow;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn;Medium",NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image generating models;openAI Reasoning models,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search for answers,Project planning;Deployment and monitoring;Learning new concepts or technologies,Documenting code;Debugging or fixing code;Testing code;Committing and reviewing code;Predictive ...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,AI agents have increased my productivity.;AI agents have reduced the time spent on specific deve...,I am concerned about the accuracy of the information provided by AI agents.;It takes significant...,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and...,The cost of using certain AI agent platforms is a barrier.;I have concerns about the security an...,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0

In [32]:
column = "Age"

survey[column].describe()

count               48745
unique                  6
top       25-34 years old
freq                16485
Name: Age, dtype: object

In [34]:
survey["Age"] = survey["Age"].fillna(
    survey["Age"].mode()[0]
)

In [37]:
survey["EdLevel"] = survey["EdLevel"].fillna(
    survey["EdLevel"].mode()[0]
)

In [40]:
survey["Employment"] = survey["Employment"].fillna(
    "Unknown"
)

In [52]:
survey["LearnCodeChoose"] = survey["LearnCodeChoose"].fillna(
    "Unknown"
)

In [51]:
survey["DevType"] = survey["DevType"].fillna(
    "Unknown"
)

In [61]:
survey["YearsCode"] = survey["YearsCode"].fillna(
    survey["YearsCode"].median()
)

In [63]:
survey["WorkExp"] = survey["WorkExp"].fillna(
    "Unknown"
)

In [67]:
survey["TechEndorseIntro"] = survey["TechEndorseIntro"].fillna("Unknown")

In [70]:
survey["PurchaseInfluence"] = survey["PurchaseInfluence"].fillna("Unknown")

In [73]:
survey["AIThreat"] = survey["AIThreat"].fillna("Unknown")

In [76]:
survey["NewRole"] = survey["NewRole"].fillna("Unknown")

In [81]:
survey["Country"] = survey["Country"].fillna("Unknown")

In [85]:
survey["Currency"] = survey["Currency"].fillna("Unknown")

In [90]:
survey["LearnCodeAI"] = survey["LearnCodeAI"].fillna("Unknown")

In [94]:
survey["OrgSize"] = survey["OrgSize"].fillna("Unknown")

In [96]:
survey["RemoteWork"] = survey["RemoteWork"].fillna("Unknown")

In [99]:
survey["AISelect"] = survey["AISelect"].fillna("Unknown")

In [102]:
survey["Industry"] = survey["Industry"].fillna("Unknown")

In [8]:
survey["LearnCode"] = survey["LearnCode"].fillna(
    survey["LearnCode"].mode()
)

In [7]:
survey["EmploymentAddl"] = survey["EmploymentAddl"].fillna("Unknown")

In [110]:
numeric_cols

Index(['ResponseId', 'WorkExp', 'YearsCode', 'TechEndorse_1', 'TechEndorse_2', 'TechEndorse_3', 'TechEndorse_4', 'TechEndorse_5', 'TechEndorse_6', 'TechEndorse_7', 'TechEndorse_8', 'TechEndorse_9',
       'TechEndorse_13', 'TechOppose_1', 'TechOppose_2', 'TechOppose_3', 'TechOppose_5', 'TechOppose_7', 'TechOppose_9', 'TechOppose_11', 'TechOppose_13', 'TechOppose_16', 'TechOppose_15',
       'JobSatPoints_1', 'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'JobSatPoints_13',
       'JobSatPoints_14', 'JobSatPoints_15', 'JobSatPoints_16', 'ToolCountWork', 'ToolCountPersonal', 'CompTotal', 'SO_Actions_1', 'SO_Actions_16', 'SO_Actions_3', 'SO_Actions_4', 'SO_Actions_5',
       'SO_Actions_6', 'SO_Actions_9', 'SO_Actions_7', 'SO_Actions_10', 'SO_Actions_15', 'ConvertedCompYearly', 'JobSat'],
      dtype='object')

In [8]:
survey['EmploymentAddl'].value_counts()

EmploymentAddl
None of the above                                                                                                                                                                                                                                                           18593
Caring for dependents (children, elderly, etc.)                                                                                                                                                                                                                              5311
Engaged in paid work (20-29 hours per week)                                                                                                                                                                                                                                  4720
Unknown                                                                                                                                                                                                                                                                      4303
Attending school (full-time)                                                                                                                                                                                                                                                 2757
                                                                                                                                                                                                                                                                            ...
Caring for dependents (children, elderly, etc.);Engaged in paid work (20-29 hours per week);Transitioning to retirement (gradually reducing work hours);Engaged in paid work (10-19 hours per week);Engaged in paid work (less than 10 hours per week)                          1
Caring for dependents (children, elderly, etc.);None of the above;Engaged in paid work (20-29 hours per week);Transitioning to retirement (gradually reducing work hours);Engaged in paid work (10-19 hours per week);Engaged in paid work (less than 10 hours per week)        1
Volunteering (regularly);Engaged in paid work (20-29 hours per week);Transitioning to retirement (gradually reducing work hours);Engaged in paid work (10-19 hours per week)                                                                                                    1
Volunteering (regularly);Engaged in paid work (20-29 hours per week);Transitioning to retirement (gradually reducing work hours);Attending school (part-time);Engaged in paid work (10-19 hours per week);Engaged in paid work (less than 10 hours per week)                    1
Engaged in paid work (20-29 hours per week);Transitioning to retirement (gradually reducing work hours);Attending school (full-time)                                                                                                                                            1
Name: count, Length: 172, dtype: int64

In [112]:
survey.to_csv('in_progress.csv', index=False)

In [4]:
survey.shape

(49123, 134)

## Standardizing Data

In [24]:
for col in categorical_cols:
    survey[col] = survey[col].str.lower()

In [25]:
for col in categorical_cols:
    survey[col] = survey[col].str.strip()

In [26]:
for col in categorical_cols:
    survey[col] = survey[col].str.replace(
        r"\s+",
        " ",
        regex=True
    )

# Replacing multiple spaces with a single space

In [27]:
for col in categorical_cols:
    survey[col] = survey[col].str.replace(
        r"[\n\r\t]",
        "",
        regex=True
    )

# Removing invisible characters

In [11]:
survey.head(2)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AIAgentImpactSomewhat agree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,i am a developer by profession,25-34 years old,"master’s degree (m.a., m.s., m.eng., mba, etc.)",employed,"caring for dependents (children, elderly, etc.)",8.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,14.0,"developer, mobile",20 to 99 employees,people manager,remote,"yes, i influenced the purchase of a substantial addition to the tech stack",work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,fintech,3.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,i'm not sure,i have neither consider or transitioned into a new career or industry,7.0,3.0,ukraine,eur european euro,52800.0,yes,bash/shell (all shells);dart;sql,dart,dart,yes,cloud firestore;postgresql,NaN,NaN,yes,amazon web services (aws);cloudflare;firebase;google cloud;gradle,NaN,NaN,no,NaN,NaN,NaN,yes,android studio;notepad++;visual studio;visual studio code;xcode,NaN,NaN,NaN,NaN,NaN,windows;macos;android,windows;macos;android;ios;ipados,confluence;github;gitlab;jira;markdown file,markdown file,markdown file,"stack overflow;reddit;github (public projects, not private repos);youtube;linkedin;medium",NaN,NaN,yes,openai gpt (chatbot models);openai image generating models;openai reasoning models,NaN,NaN,yes,a few times per week,between 5 and 10 years,i have never participated in q&a on stack overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,neutral,"rarely, almost never","yes, i use ai tools monthly or infrequently",indifferent,neither trust nor distrust,bad at handling complex tasks,learning about a codebase;writing code;search for answers,project planning;deployment and monitoring;learning new concepts or technologies,documenting code;debugging or fixing code;testing code;committing and reviewing code;predictive ...,NaN,NaN,"ai solutions that are almost right, but not quite",no,"yes, i use ai agents at work monthly or infrequently",not at all or minimally,software engineering,ai agents have increased my productivity.;ai agents have reduced the time spent on specific deve...,i am concerned about the accuracy of the information provided by ai agents.;it takes significant...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,the cost of using certain ai agent platforms is a barrier.;i have concerns about the security an...,NaN,when i don’t trust ai’s answers,"troubleshooting, profiling, debugging",61256.0,10.0
1,2,i am a developer by profession,25-34 years old,"associate degree (a.a., a.s., etc.)",employed,NaN,2.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,10.0,"developer, back-end",500 to 999 employees,individual contributor,"hybrid (some in-person, leans heavy to flexibility)",no,personal project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,retail and consumer services,10.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,i'm not sure,i have transitioned into a new career and/or industry voluntarily,6.0,5.0,netherlands,eur european euro,90000.0,yes,java,java;python;swift,java,yes,dynamodb;mongodb,dynamodb;mongodb,dynamodb;mongodb,yes,amazon web services (aws);datadog;docker;homebrew;kubernetes;maven (build tool);terraform,amazon web services (aws);datadog;docker;homebrew;kubernetes;maven (build tool);terraform,amazon web services (aws);datadog;docker;homebrew;kubernetes;maven (build tool);terraform,yes,spring boot,spring boot,spring boot,yes,intellij idea;pycharm;visual studio code;xcode,intellij idea;pycharm;visual studio code;xcode,intellij idea;pycharm;visual studio code;xcode,NaN,NaN,NaN,windows;macos;ios;ipados,macos,confluence;github;jira,confluence;github;jira,confluence;github;jira,"stack overflow;discord;reddit;dev.to;hacker news;github (public projects, not private repos);sla...","stack overflow;discord;reddit;dev.to;hacker news;github (public projects, not private repos);sla...","stack overflow;discord;reddit;dev.to;hacker news;github (public projects, not private repos);sla...",yes,openai gpt (chatbot models),openai gpt (chatbot models),openai gpt (chatbot models),not sure/can't remember,multiple times per day,between 10 and 15 years,"infrequently, less than once per year",chat (people);message boards;long-form articles;videos;coding challenges;logic games/puzzles;lis...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,"yes, somewhat",about half of the time,"yes, i use ai tools weekly",indifferent,neither trust nor distrust,bad at handling complex tasks,learning new concepts or technologies,learning about a codebase;project planning;committing and reviewing code;deployment and monitoring,writing code;documenting code;debugging or fixing code;testing code;predictive analytics;search ...,NaN,NaN,"ai solutions that are almost right, but not quite;debugging ai-generated code is more time-consu...",no,"no, and i don't plan to",not at all or minimally,NaN,NaN,it takes significant time and effort to learn how to use ai agents effectively.;the cost of usin...,NaN,i am concerned about the accuracy of the information provided by ai agents.;i have concerns abou...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,when i don’t trust ai’s answers;when i want to fully understand something;when i want to learn b...,all skills. ai is a flop.,104413.0,9.0

In [43]:
survey["LanguageHaveWorkedWith"].unique()

array(['bash/shell (all shells);dart;sql', 'java',
       'dart;html/css;javascript;typescript', ...,
       'ada;assembly;erlang;f#;fortran;gdscript;go;groovy',
       'c++;dart;gdscript;html/css;javascript;php;powershell;python;r;sql',
       'bash/shell (all shells);delphi;powershell;python;sql'],
      shape=(15468,), dtype=object)

In [28]:
language_counts = (
    survey['LanguageHaveWorkedWith']
    .dropna()
    .str.lower()
    .str.split(';')
    .explode()
    .str.strip()
    .unique()
)

language_counts

array(['bash/shell (all shells)', 'dart', 'sql', 'java', 'html/css',
       'javascript', 'typescript', 'kotlin', 'c', 'c#', 'c++', 'delphi',
       'lua', 'powershell', 'python', 'vba', 'visual basic (.net)',
       'scala', 'ada', 'assembly', 'cobol', 'elixir', 'erlang', 'f#',
       'fortran', 'gdscript', 'go', 'groovy', 'lisp', 'matlab',
       'micropython', 'ocaml', 'perl', 'php', 'prolog', 'r', 'ruby',
       'rust', 'swift', 'zig', 'mojo', 'gleam'], dtype=object)

In [45]:
survey.shape

(49123, 134)

In [22]:
survey = pd.read_csv("in_progress.csv")

In [23]:
survey.shape

(49123, 134)

In [29]:
survey.head(2)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AIAgentImpactSomewhat agree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,i am a developer by profession,25-34 years old,"master’s degree (m.a., m.s., m.eng., mba, etc.)",employed,"caring for dependents (children, elderly, etc.)",8.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,14.0,"developer, mobile",20 to 99 employees,people manager,remote,"yes, i influenced the purchase of a substantial addition to the tech stack",work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,fintech,3.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,i'm not sure,i have neither consider or transitioned into a new career or industry,7.0,3.0,ukraine,eur european euro,52800.0,yes,bash/shell (all shells);dart;sql,dart,dart,yes,cloud firestore;postgresql,NaN,NaN,yes,amazon web services (aws);cloudflare;firebase;google cloud;gradle,NaN,NaN,no,NaN,NaN,NaN,yes,android studio;notepad++;visual studio;visual studio code;xcode,NaN,NaN,NaN,NaN,NaN,windows;macos;android,windows;macos;android;ios;ipados,confluence;github;gitlab;jira;markdown file,markdown file,markdown file,"stack overflow;reddit;github (public projects, not private repos);youtube;linkedin;medium",NaN,NaN,yes,openai gpt (chatbot models);openai image generating models;openai reasoning models,NaN,NaN,yes,a few times per week,between 5 and 10 years,i have never participated in q&a on stack overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,neutral,"rarely, almost never","yes, i use ai tools monthly or infrequently",indifferent,neither trust nor distrust,bad at handling complex tasks,learning about a codebase;writing code;search for answers,project planning;deployment and monitoring;learning new concepts or technologies,documenting code;debugging or fixing code;testing code;committing and reviewing code;predictive ...,NaN,NaN,"ai solutions that are almost right, but not quite",no,"yes, i use ai agents at work monthly or infrequently",not at all or minimally,software engineering,ai agents have increased my productivity.;ai agents have reduced the time spent on specific deve...,i am concerned about the accuracy of the information provided by ai agents.;it takes significant...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,the cost of using certain ai agent platforms is a barrier.;i have concerns about the security an...,NaN,when i don’t trust ai’s answers,"troubleshooting, profiling, debugging",61256.0,10.0
1,2,i am a developer by profession,25-34 years old,"associate degree (a.a., a.s., etc.)",employed,NaN,2.0,"yes, i am not new to coding but am learning new coding techniques or programming language",online courses or certification (includes all media types);other online resources (e.g. standard...,"yes, i learned how to use ai-enabled tools for my personal curiosity and/or hobbies",ai codegen tools or ai-enabled apps,10.0,"developer, back-end",500 to 999 employees,individual contributor,"hybrid (some in-person, leans heavy to flexibility)",no,personal project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,retail and consumer services,10.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,i'm not sure,i have transitioned into a new career and/or industry voluntarily,6.0,5.0,netherlands,eur european euro,90000.0,yes,java,java;python;swift,java,yes,dynamodb;mongodb,dynamodb;mongodb,dynamodb;mongodb,yes,amazon web services (aws);datadog;docker;homebrew;kubernetes;maven (build tool);terraform,amazon web services (aws);datadog;docker;homebrew;kubernetes;maven (build tool);terraform,amazon web services (aws);datadog;docker;homebrew;kubernetes;maven (build tool);terraform,yes,spring boot,spring boot,spring boot,yes,intellij idea;pycharm;visual studio code;xcode,intellij idea;pycharm;visual studio code;xcode,intellij idea;pycharm;visual studio code;xcode,NaN,NaN,NaN,windows;macos;ios;ipados,macos,confluence;github;jira,confluence;github;jira,confluence;github;jira,"stack overflow;discord;reddit;dev.to;hacker news;github (public projects, not private repos);sla...","stack overflow;discord;reddit;dev.to;hacker news;github (public projects, not private repos);sla...","stack overflow;discord;reddit;dev.to;hacker news;github (public projects, not private repos);sla...",yes,openai gpt (chatbot models),openai gpt (chatbot models),openai gpt (chatbot models),not sure/can't remember,multiple times per day,between 10 and 15 years,"infrequently, less than once per year",chat (people);message boards;long-form articles;videos;coding challenges;logic games/puzzles;lis...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,"yes, somewhat",about half of the time,"yes, i use ai tools weekly",indifferent,neither trust nor distrust,bad at handling complex tasks,learning new concepts or technologies,learning about a codebase;project planning;committing and reviewing code;deployment and monitoring,writing code;documenting code;debugging or fixing code;testing code;predictive analytics;search ...,NaN,NaN,"ai solutions that are almost right, but not quite;debugging ai-generated code is more time-consu...",no,"no, and i don't plan to",not at all or minimally,NaN,NaN,it takes significant time and effort to learn how to use ai agents effectively.;the cost of usin...,NaN,i am concerned about the accuracy of the information provided by ai agents.;i have concerns abou...,integrating ai agents with my existing tools and workflows can be difficult.;my company's it and...,when i don’t trust ai’s answers;when i want to fully understand something;when i want to learn b...,all skills. ai is a flop.,104413.0,9.0

In [14]:
languages = survey["LanguageHaveWorkedWith"].str.get_dummies(sep=";")

In [15]:
languages.head()

,ada,assembly,bash/shell (all shells),c,c#,c++,cobol,dart,delphi,elixir,erlang,f#,fortran,gdscript,gleam,go,groovy,html/css,java,javascript,kotlin,lisp,lua,matlab,micropython,mojo,ocaml,perl,php,powershell,prolog,python,r,ruby,rust,scala,sql,swift,typescript,vba,visual basic (.net),zig
0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4,0,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,1,1,1,0

In [ ]:
survey = pd.concat(
    [survey, languages],
    axis=1
)

In [16]:
survey = pd.concat(
    [survey, languages],
    axis=1
)

In [20]:
survey['DevEnvsAdmired'].value_counts().head(50)

DevEnvsAdmired
visual studio code                                          2342
visual studio;visual studio code                             768
notepad++;visual studio;visual studio code                   573
neovim                                                       541
intellij idea                                                405
vim;visual studio code                                       386
notepad++;visual studio code                                 315
intellij idea;visual studio code                             313
cursor;visual studio code                                    268
cursor                                                       259
visual studio                                                256
vim                                                          229
jupyter notebook/jupyterlab;visual studio code               218
notepad++;visual studio                                      205
neovim;vim                                                   181
neovim;visual studio code                                    167
zed                                                          161
nano;visual studio code                                      152
android studio;visual studio code                            109
sublime text;visual studio code                              100
claude code;visual studio code                                96
notepad++                                                     96
neovim;vim;visual studio code                                 93
visual studio code;zed                                        88
phpstorm                                                      87
notepad++;vim;visual studio code                              84
rider;visual studio code                                      84
pycharm                                                       84
intellij idea;notepad++                                       81
visual studio code;xcode                                      81
pycharm;visual studio code                                    79
neovim;zed                                                    77
xcode                                                         75
vscodium                                                      74
intellij idea;vim;visual studio code                          72
intellij idea;vim                                             71
rider;visual studio;visual studio code                        64
android studio;visual studio code;xcode                       63
webstorm                                                      62
jupyter notebook/jupyterlab;notepad++;visual studio code      61
jupyter notebook/jupyterlab;vim;visual studio code            61
intellij idea;notepad++;visual studio code                    60
android studio                                                55
nano;notepad++;visual studio code                             55
vim;visual studio;visual studio code                          53
intellij idea;neovim                                          52
visual studio code;windsurf                                   51
rider                                                         49
visual studio code;vscodium                                   47
android studio;intellij idea;visual studio code               46
Name: count, dtype: int64

In [21]:
# Split temporarily
languages = survey["LanguageHaveWorkedWith"].str.split(";")

# Flatten all responses
all_languages = languages.explode()

# Count frequencies
language_counts = (
    all_languages
    .value_counts()
    .head(20)
)

print(language_counts)

LanguageHaveWorkedWith
javascript                 20986
html/css                   19681
sql                        18617
python                     18388
bash/shell (all shells)    15486
typescript                 13852
java                        9344
c#                          8845
c++                         7479
powershell                  7366
c                           6979
php                         5990
go                          5213
rust                        4717
kotlin                      3418
lua                         2906
assembly                    2244
ruby                        2046
dart                        1882
swift                       1718
Name: count, dtype: int64

In [30]:
survey.to_csv("work_in_progress", index=False)

In [3]:
survey = pd.read_csv("work_in_progress")

In [5]:
survey.shape

(49123, 134)